version: '3'

services:
  node:
    image: node:16-alpine3.16
    container_name: node
    hostname: node
    working_dir: '/app'
    volumes:
      - './:/app'
    command: 'sh -c "npm install && npm start"'
    network_mode: host